sonar.projectKey=rabestro_home-genie
sonar.organization=rabestro

# Source and Test paths
sonar.sources=src
sonar.tests=tests

# Encoding & Language settings
sonar.sourceEncoding=UTF-8
sonar.python.version=3.14

# Exclusions
sonar.exclusions=**/venv/**,**/.venv/**,**/__pycache__/**,uv.lock
